<
	{log[a]}
	{test[false]}
	{true:
		{print[data:1]}
		{print[data:2]}
	}
	{false:
		{print[data:3]}
		{print[data:4]}
	}
	{test[true]}
	{true:
		{print[data:5]}
		{print[data:6]}
	}
	{false:
		{print[data:7]}
		{print[data:8]}
	}
	
	{test[1+4]}
	{1:
		{print[data:9]}
	}
	{2:
		{print[data:10]}
	}
	{4:
		{print[data:11]}
	}
	{2:
		{print[data:12]}
	}
	{4:
		{print[data:13]}
	}
	
	
	{log[flush:a storage:"file://./samples/test.bs"]}
	{print[file:"./samples/test.bs"]}
	{$clipboard}
>